#ifndef OSOSCAR_H
#define OSOSCAR_H

/* *******************************************************************************************************
 * OSOSCAR Class
 * v1.0 13/07/2018
 * class to store OSCAR data generated by the OSCAR-tool program
 * implemented by Daniele Dell'Aquila (dellaquila.daniele@gmail.com)
 * 
 * The class is composed by:
 * 1 OSOSCARCluster
 *
 *
 * class OSOSCARCluster : it contains an array of OSOSCARTelescope objects
 *
 * - OSOSCARTelescope
 * | - OSStrip
 * | - OSPad
 */

#include <TTree.h>
#include <OSDetector.h>
#include <OSOSCARRootEvent.h>

#include <OSCARShared.h>

class OSOSCAR : public OSDetector
{
public :
  OSOSCAR(const char *, int);                      //!Constructor
  ~OSOSCAR();                                      //!Destructor

  void Clear() override;                           //!Clear. Not used in the current implementation.

  void InitTTreeBranch(TTree *) override;          //!Initialize TTree Branch containing detector ROOT type
  void BuildEvent() override;                      //!Calls individual electronic modules to feel detector branches
  void FillMappedData() override;                  //!Stores mapped data in detector ROOT class to be written on the output tree

private :
//   OSOSCARCluster * fOSCARMapped;                    //!OSOSCARCluster containing event-by-event mapped data of the entire cluster of OSCAR telescopes (in the trivial case just 1)
  OSOSCARRootEvent * fevt;                         //!RootEvent type of the detector

};

#endif